### PR TITLE
docs: Updated documentation according to new implementation of routers

### PR DESCRIPTION
**Pull request by rehanedly**
**Description:** Updated documentation for xAPI transformation and multiple routers support for one backend

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc.

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @rehanedly! I've created [OSPR-5831](https://openedx.atlassian.net/browse/OSPR-5831) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@rehanedly Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by natabene** [comment]
@ziafazal Are you planning to review this as a core committer?

**Review by ziafazal — APPROVED** [review]
👍

**Comment by feanil** [comment]
Generally looks good to me as well but looks like there is a conflict. @rehanedly can you resolve the conflict.

**Review by feanil — APPROVED** [review]
For clarity, I think this is good to merge after the conflict is resolved.  @ziafazal I believe you have merge access but let me know if you need me for any of the mechanics.

**Comment by natabene** [comment]
@rehanedly Please resolve conflicts when you have a chance.

**Comment by rehanedly** [comment]
closing this in-favour of [#129](https://github.com/edx/event-routing-backends/pull/129).

**Comment by edx-webhook** [comment]
@rehanedly Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/event-routing-backends&entry.867055334=https://github.com/edx/event-routing-backends/pull/79&entry.1484655318=https://github.com/rehanedly&entry.752974735=2021-06-03+14:28&entry.1917517419=2021-09-28+07:59&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
