### PR TITLE
Removed any unnecessary data being passed to backend in extensions

### PR DESCRIPTION
**Pull request by sheralim012**
To make sure we are passing only useful data to caliper/xAPI LRS this PR removes unnecessary data.
In addition to security risk involved sometimes this data makes xAPI statements invalid i.e code being passed to video events.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @sheralim012! I've created [OSPR-5698](https://openedx.atlassian.net/browse/OSPR-5698) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by ziafazal — APPROVED** [review]
👍

**Comment by edx-webhook** [comment]
@sheralim012 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/event-routing-backends&entry.867055334=https://github.com/edx/event-routing-backends/pull/62&entry.1484655318=https://github.com/sheralim012&entry.752974735=2021-03-29+14:36&entry.1917517419=2021-03-30+06:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@sheralim012 Thank you for your contribution.

**Pull request merged**
