### PR TITLE
Removed referrer

### PR DESCRIPTION
**Pull request by ziafazal**
This PR has following changes

1. Removes referrer since reference url can have sensitive info
2. Type check in `find_nested` method
3. Removed necessary data passed in `extensions` field

**Installation instructions:** List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by ziafazal** [comment]
@feanil  @timmc-edx could you please review this PR?

**Comment by timmc-edx** [comment]
It would be really helpful if this could be broken into at least two separate PRs -- one to remove referer, another to change how `find_nested` works. It's hard to review the two changes combined, especially with the large number of files touched.

**Comment by ziafazal** [comment]
@timmc-edx changeset looks large how it touches only 12 python files rest of the files are json test expected input files.

**Comment by timmc-edx** [comment]
I know, but the changed are still entangled -- I have to figure out which of those test data changes are from which of the Python changes, and that's going to delay review.

**Comment by timmc-edx** [comment]
Could you please break this apart and submit as separate PRs, each of which expresses a single logical change? That breakdown might look something like:

1. Removing referer, and removing of other fields using `extract_subdict_by_keys` (not sure if these should be separate PRs -- they both sound like behavior changes in the same vein)
2. Applying a type check to the find_nested call
3. Any other cleanups or fixes that are highly separated from each other in the code, don't have a large surface area, but are small enough that they can go in the same PR

In general, using separate, tightly-focused commits (or PRs) is important for making the code easy for the reviewer (and later developers looking at commit history) to understand. (Separating refactors from behavior changes is also important.)

**Comment by ziafazal** [comment]
@timmc-edx closing this in favour of #46

**Pull request closed without merging**
