### PR TITLE
Add settings to safeguard against accidental enabling of Caliper/xAPI

### PR DESCRIPTION
**Pull request by timmc-edx**
ARCHBOM-1658

**Merge checklist:**
- [ ] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings)

### CODE REVIEW

**Review by feanil — APPROVED** [review]

**Review by feanil — COMMENTED** [review]
Should we add some tests for this change?

**Comment by timmc-edx** [comment]
Yeah, and I think (I hope) that I need to adjust current tests to account for the new setting. Needs doc too.

**Comment by timmc-edx** [comment]
Quick review of test and doc?

**Comment by timmc-edx** [comment]
Tested in devstack -- confirmed that events are now blocked by default, and adding setting = True unblocks them.

**Pull request merged**
